---
title: "elections_maricopa"
author: "Wesley Chioh"
date: "October 17, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

maricopa_2012_results <- read_csv("Maricopa_2012.txt")
maricopa_2014_results <- read_tsv("Maricopa_2014.txt")
maricopa_2016_results <- read_tsv("Maricopa_2016.txt")
maricopa_2018_results <- read_tsv("Maricopa_2018.txt")
```

## Maricopa County's Elections

First, I will try to parse for congressinal elections in each of the 724 precincts in Maricopa County, AZ. 

```{r elections_congress}
# filter for congressional races and basic calculations of winning margins
congress_filter <- function(df){
  congress_races <- df %>%
    filter(str_detect(CONTEST_FULL_NAME, "US Rep ")) %>%
    select(PRECINCT_NAME, CANDIDATE_FULL_NAME, candidate_party_id, CONTEST_FULL_NAME, TOTAL, PRECINCT_ID, CONTEST_TOTAL) %>%
    mutate(TOTAL_PCT = ifelse(TOTAL != 0, TOTAL/CONTEST_TOTAL, 0)) %>%
    group_by(PRECINCT_ID) %>%
    arrange(desc(TOTAL)) %>%
    mutate(CANDIDATE_PARTY = ifelse(candidate_party_id == 1, "REP",
                                    ifelse(candidate_party_id == 2, "DEM", "OTHERS")), 
            WINNER = first(CANDIDATE_FULL_NAME),
            WINNING_PARTY = substr(WINNER, 1, 3),
            MARGIN_PCT = first(TOTAL_PCT)-nth(TOTAL_PCT, n = 2),
            MARGIN = first(TOTAL) - nth(TOTAL, n = 2)) %>%
    ungroup() %>%
    arrange(PRECINCT_ID)
  # congress_races$TOTAL_PCT <- na_if(congress_races$TOTAL_PCT, NaN)
  # congress_races$TOTAL_PCT <- replace_na(congress_races$TOTAL_PCT, 0)
  # congress_races$MARGIN_PCT <- na_if(congress_races$MARGIN_PCT, NaN)
  # congress_races$MARGIN_PCT <- replace_na(congress_races$MARGIN_PCT, 0)
  congress_races
}

# pivot to wider table for each precinct
tidy_congress_election_data <- function(df, csv, location){
  tidy_df <- df %>%
    filter(candidate_party_id %in% c(1, 2)) %>%
    pivot_wider(id_cols = c(PRECINCT_NAME, CANDIDATE_FULL_NAME, CONTEST_FULL_NAME, CONTEST_TOTAL,
                            WINNER, WINNING_PARTY, MARGIN_PCT, MARGIN
                            ), 
                values_from = c(CANDIDATE_FULL_NAME, TOTAL, TOTAL_PCT), 
                names_from = CANDIDATE_PARTY)
  tidy_df <- tidy_df[,c("PRECINCT_NAME", "CONTEST_FULL_NAME", "CANDIDATE_FULL_NAME_REP", "CANDIDATE_FULL_NAME_DEM", 
                        "CONTEST_TOTAL", "TOTAL_REP", "TOTAL_DEM", "TOTAL_PCT_REP", "TOTAL_PCT_DEM", 
                        "MARGIN", "MARGIN_PCT", "WINNER", "WINNING_PARTY"
                        )]
  if(csv == T){
    write_csv(tidy_df, path = location)
  }
    
  tidy_df
}

# The following precincts (years) were duplicated for some unidentifable reason. They will have to be corrected manually
## Precincts: SUNFLOWER (2012-2018), HICKIWAN (2014), LONE BUTTE (2014), TORTILLA FLAT (2014)

maricopa_2012_congress <- maricopa_2012_results %>%
  congress_filter() %>%
  tidy_congress_election_data(csv = T, location = "./CongressRaceResults/maricopa_2012.csv")
maricopa_2014_congress <- maricopa_2014_results %>%
  congress_filter() %>%
  tidy_congress_election_data(csv = T, location = "./CongressRaceResults/maricopa_2014.csv")
maricopa_2016_congress <- maricopa_2016_results %>%
  congress_filter() %>%
  tidy_congress_election_data(csv = T, location = "./CongressRaceResults/maricopa_2016.csv")
maricopa_2018_congress <- maricopa_2018_results %>%
  congress_filter() %>%
  tidy_congress_election_data(csv = T, location = "./CongressRaceResults/maricopa_2018.csv")

```
