---
title: "MaricopaCounty"
author: "Wesley Chioh"
date: "October 7, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(tidycensus)
library(tidyverse)
options(tigris_use_cache = T)
```

## Maricopa County  

How has Maricopa County changed between the elections?

```{r loading}
# # 2019
# maricopa_basics_2019 <- get_acs(geography = "tract",
#                                 survey = "acs1",
#                                 state = "AZ",
#                                 county = "Maricopa",
#                                 year = 2019,
#                                 variables = c(med_income = "B06011_001", med_age = "B01002_001", total_pop = "B01001_001"))
# maricopa_demographics_2019 <- get_acs(geography = "tract",
#                                       state = "AZ",
#                                       county = "Maricopa",
#                                       year = 2019,
#                                       variables = c(white = "B03002_003", hispanic = "B03002_012", black = "B03002_004", 
#                                                     asian = "B03002_006", native = "B03002_005")) 

# 2018
maricopa_basics_2018 <- get_acs(geography = "tract",
                                state = "AZ",
                                county = "Maricopa",
                                year = 2018,
                                geometry = F,
                                variables = c(med_income = "B19013_001", med_age = "B01002_001", total_pop = "B00001_001"))
maricopa_basics_2018_shp <- get_acs(geography = "tract",
                                state = "AZ",
                                county = "Maricopa",
                                year = 2018,
                                geometry = T,
                                variables = c(med_income = "B19013_001", med_age = "B01002_001", total_pop = "B00001_001"))
maricopa_demographics_2018 <- get_acs(geography = "tract",
                                      state = "AZ",
                                      county = "Maricopa",
                                      year = 2018,
                                      variables = c(white = "B03002_003", hispanic = "B03002_012", black = "B03002_004", 
                                                    asian = "B03002_006", native = "B03002_005")) 

# 2017
maricopa_basics_2017 <- get_acs(geography = "tract",
                                state = "AZ",
                                county = "Maricopa",
                                year = 2017,
                                variables = c(med_income = "B19013_001", med_age = "B01002_001", total_pop = "B00001_001"))
maricopa_demographics_2017 <- get_acs(geography = "tract",
                                      state = "AZ",
                                      county = "Maricopa",
                                      year = 2017,
                                      variables = c(white = "B03002_003", hispanic = "B03002_012", black = "B03002_004", 
                                                    asian = "B03002_006", native = "B03002_005"))
# 2016
maricopa_basics_2016 <- get_acs(geography = "tract",
                                state = "AZ",
                                county = "Maricopa",
                                year = 2016,
                                variables = c(med_income = "B19013_001", med_age = "B01002_001", total_pop = "B00001_001"))
maricopa_demographics_2016 <- get_acs(geography = "tract",
                                      state = "AZ",
                                      county = "Maricopa",
                                      year = 2016,
                                      variables = c(white = "B03002_003", hispanic = "B03002_012", black = "B03002_004", 
                                                    asian = "B03002_006", native = "B03002_005")) 

# 2015
maricopa_basics_2015 <- get_acs(geography = "tract",
                                state = "AZ",
                                county = "Maricopa",
                                year = 2015,
                                variables = c(med_income = "B19013_001", med_age = "B01002_001", total_pop = "B00001_001"))
maricopa_demographics_2015 <- get_acs(geography = "tract",
                                      state = "AZ",
                                      county = "Maricopa",
                                      year = 2015,
                                      variables = c(white = "B03002_003", hispanic = "B03002_012", black = "B03002_004", 
                                                    asian = "B03002_006", native = "B03002_005")) 
# 2014
maricopa_basics_2014 <- get_acs(geography = "tract",
                                state = "AZ",
                                county = "Maricopa",
                                year = 2014,
                                variables = c(med_income = "B19013_001", med_age = "B01002_001", total_pop = "B00001_001"))
maricopa_demographics_2014 <- get_acs(geography = "tract",
                                      state = "AZ",
                                      county = "Maricopa",
                                      year = 2014,
                                      variables = c(white = "B03002_003", hispanic = "B03002_012", black = "B03002_004", 
                                                    asian = "B03002_006", native = "B03002_005")) 

# 2013
maricopa_basics_2013 <- get_acs(geography = "tract",
                                state = "AZ",
                                county = "Maricopa",
                                year = 2013,
                                variables = c(med_income = "B19013_001", med_age = "B01002_001", total_pop = "B00001_001"))
maricopa_demographics_2013 <- get_acs(geography = "tract",
                                      state = "AZ",
                                      county = "Maricopa",
                                      year = 2013,
                                      variables = c(white = "B03002_003", hispanic = "B03002_012", black = "B03002_004", 
                                                    asian = "B03002_006", native = "B03002_005")) 

# 2012
maricopa_basics_2012 <- get_acs(geography = "tract",
                                state = "AZ",
                                county = "Maricopa",
                                year = 2012,
                                variables = c(med_income = "B19013_001", med_age = "B01002_001", total_pop = "B00001_001"))
maricopa_demographics_2012 <- get_acs(geography = "tract",
                                      state = "AZ",
                                      county = "Maricopa",
                                      year = 2012,
                                      variables = c(white = "B03002_003", hispanic = "B03002_012", black = "B03002_004", 
                                                    asian = "B03002_006", native = "B03002_005")) 
```

Saving the data into CSVs and RDS for analysis

```{r RDS and CSV, echo=FALSE}
demographics_objects_list <- list(maricopa_basics_2012, maricopa_basics_2013, maricopa_basics_2014, maricopa_basics_2015, maricopa_basics_2016, maricopa_basics_2017, maricopa_basics_2018, maricopa_demographics_2012, maricopa_demographics_2013, maricopa_demographics_2014, maricopa_demographics_2015, maricopa_demographics_2016, maricopa_demographics_2017, maricopa_demographics_2018)
demographics_objects_namelist <- c("maricopa_basics_2012", "maricopa_basics_2013", "maricopa_basics_2014", "maricopa_basics_2015", "maricopa_basics_2016", "maricopa_basics_2017", "maricopa_basics_2018", "maricopa_demographics_2012", "maricopa_demographics_2013", "maricopa_demographics_2014", "maricopa_demographics_2015", "maricopa_demographics_2016", "maricopa_demographics_2017", "maricopa_demographics_2018")
sapply(1:14, function(x){
  write_csv(as.data.frame(demographics_objects_list[x]), path = paste("./Demographics/", demographics_objects_namelist[x], ".csv", sep = ""))
  saveRDS(demographics_objects_list[x], paste("./Demographics/", demographics_objects_namelist[x], ".RDS", sep = ""))
})
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
